server:
  # ????
  port: 8000

spring:
  security:
    oauth2:
      client:
        provider:
          # ?????,?????
          custom-issuer:
            # Token????(??????)
            issuer-uri: http://10.10.20.66:8080
            # ?????????????/userinfo????IdToken??????????????????
            user-info-uri: ${spring.security.oauth2.client.provider.custom-issuer.issuer-uri}/user
        registration:
          # registration Id????
          messaging-client-oidc:
            # oauth???????????????????????
            provider: custom-issuer
            # ?????????
            client-name: message-client
            # ???id????????????id
            client-id: messaging-client
            # ?????
            client-secret: 123456
            # ???????
            client-authentication-method: client_secret_basic
            # ??Token???????
            authorization-grant-type: authorization_code
            # ??????????Spring Security Client??????code??token???
            redirect-uri: http://127.0.0.1:8000/login/oauth2/code/messaging-client-oidc
            scope:
              - message.read
              - message.write
